% figure_variance_explained.m
%
% Script for generating the horizontal bar-chart figure of variance
% explained by each variable in the GLM, for use with the Sickle-UK data
% set, with statistics generated by SICKLE_GLM_ANALYSIS.m
% 
%
%       Copyright (C) University College London, 2025
%
%
% Created by MT Cherukara, April 2024
%
% CHANGELOG:
%
% 2025-03-11 (MTC). Refactored and brought into alignment with the other
%       scripts in this folder, ready for the paper.

clearvars;

%% Select Data

% Load in the data
load('SickleUK_GLMResultsBG_QSM.mat')
load('ROI_names_BG.mat');

% We only want to plot certain significant ROIs
sign_rois = find(res_pv < 0.05);
nrois = length(sign_rois);


%% Process 

% Nice ROI names, for displaying
roi_names_nice = {' L. Caudate Nucleus';' R. Caudate Nucleus';...
                  ' L. Globus Pallidus';' R. Globus Pallidus';...
                  ' L. Putamen';' R. Putamen';...
                  ' L. Thalamus';' R. Thalamus';...
                  ' L. Pulvinar';' R. Pulvinar';...
                  ' L. Subthalamic Nucleus';' R. Subthalamic Nucleus';...
                  ' L. Substantia Nigra';' R. Substantia Nigra';...
                  ' L. Red Nucleus';' R. Red Nucleus';...
                  ' L. Dentate';'R. Dentate';... %};
                  ' Basal Ganglia'};
roi_names_nice = roi_names_nice(sign_rois);

% Extract only the significant names
roi_names = roi_names(sign_rois);

% Extract only the significant columns
arr_Rsquared = arr_Rsquared(:,sign_rois);

% % Combine left and right pegboard scores
% arr_Rsquared(end+1,:) = arr_Rsquared(4,:) + arr_Rsquared(5,:);
% arr_Rsquared(4:5,:) = [];

% Subtract variance explained by Age from that of Pegboard score
arr_Rsquared(end,:) = arr_Rsquared(end,:) - arr_Rsquared(1,:);

% Set any negative values equal to 0
arr_Rsquared(arr_Rsquared < 0) = 0;

% Unexplained variance
arr_Rsquared(end+1,:) = ones(1,nrois) - sum(arr_Rsquared,1);

% These are the names for the rows of "arr_Rsquared"
var_names = {'Age'; 'Sex'; 'Group'; 'Pegboard'; 'Unexplained'};


%% Plot the Graph

% Bar Chart
figure('WindowStyle','Normal','Position',[100,200,1100,500]);
b = barh(flip(100.*arr_Rsquared',1),'Stacked');
box off;
yticklabels(flip(roi_names_nice));
xlabel('Variance Explained (%)');

% Set colours
b(1).FaceColor = [147,  39,  44]./255;  % UCL Mid Red 100%
b(2).FaceColor = [  0,  43,  85]./255;  % UCL Mid Blue 100%
b(3).FaceColor = [143, 153,  62]./255;  % UCL Mid Green 100%
b(4).FaceColor = [249, 190,   0]./255;  % UCL Yellow 100%
b(5).FaceColor = [ 98,  32, 113]./255;  % UCL Mid Purple 90%
b(6).FaceColor = [152, 143, 134]./255;  % UCL Grey 90%

% Background colour
% set(gcf,'color',[201, 147, 150]./255);
% set(gca,'color',[201, 147, 150]./255);

% Set y axis limits
set(gca,'YLim',[0.6,length(roi_names)+0.4]);
set(gca,'FontSize',18);