% figure_ROI_boxplots.m
%
% Script for generating box plots showing regional susceptibility values in
% deep-brain grey matter ROIs, comparing Healthy Controls with SCA
% patients, based on data from the Sickle-UK dataset. Data should be
% generated by SICKLE_EXTRACT_AVERAGES.m
% 
%
%       Copyright (C) University College London, 2025
%
%
% Created by MT Cherukara, January 2024
%
% CHANGELOG:
%
% 2025-03-11 (MTC). Refactored and brought into alignment with the other
%       scripts in this folder, ready for the paper.


clearvars;

% Define UCL colors
colour.g = [143, 153,  62]./255;  % UCL Mid Green 100%
colour.p = [ 98,  32, 113]./255;  % UCL Mid Purple 90%

%% Input

% Load the data
load('SickleUK_QSMdata_BGanglia.mat');
load('ROI_names.mat');

% Data Quantities
n_subs = height(tbl_all);
n_rois = length(roi_names);

% Extract a logical vector for healthy controls
is_hc = strcmp(tbl_all.Group,'HC');

% Pre-allocate array for storing data
mat_QSM = zeros(n_subs,n_rois);
mat_R2s = zeros(n_subs,n_rois);

% Loop through ROIs
for rr = 1:n_rois

    % ROI name
    rname = roi_names{rr};

    % Extract susceptibility for this ROI
    vec_QSM = tbl_all.(strcat('QSM_',rname));
    vec_R2s = tbl_all.(strcat('R2s_',rname));

    % Store susceptibility
    mat_QSM(:,rr) = vec_QSM;
    mat_R2s(:,rr) = vec_R2s;

end % for rr = 1:n_rois


%% Box Plot Labels

% Create Label arrays
label_hc = repmat(is_hc,1,n_rois);
label_rois = repmat(1:n_rois,n_subs,1);

% ROI titles
roi_titles = {'L. Caudate N.';  'R. Caudate N.';...
              'L. G.P.';        'R. G.P.';...
              'L. Putamen';     'R. Putamen';...
              'L. Thalamus';    'R. Thalamus';...
              'L. Pulvinar';    'R. Pulvinar';...
              'L. Subthal. N.'; 'R. Subthal. N.';...
              'L. S. Nigra';    'R. S. Nigra';...
              'L. Red N.';      'R. Red N.';...
              'L. Dentate';     'R. Dentate';...
              'Basal Ganglia'};


%% Sort the ROIs into 'basal ganglia' and non-basal ganglia 

vec_neworder = [3,4,13,14,9,10,1,2,5,6,19,7,8,11,12,15:18];

roi_titles = roi_titles(vec_neworder);
mat_QSM = mat_QSM(:,vec_neworder);
mat_R2s = mat_R2s(:,vec_neworder);


%% Do significance testing for correlations

% Pre-allocate results
pval_QSM = zeros(n_rois,1);
pval_R2s = zeros(n_rois,1);

for rr = 1:n_rois

    % Pull out the current set of susc and R2* values
    vec_QSM = mat_QSM(:,rr);
    vec_R2s = mat_R2s(:,rr);

    % Do two-way t-test
    [~,pval_QSM(rr)] = ttest2(vec_QSM(~is_hc),vec_QSM(is_hc));
    [~,pval_R2s(rr)] = ttest2(vec_R2s(~is_hc),vec_R2s(is_hc));

end % for rr = 1:n_rois 


%% Box Plot of QSM Values

gsp = 0.01; % spacing variable for the significance stars

% Max and min values for the y-axis
chi_min = min(mat_QSM(:));
chi_max = max(mat_QSM(:));

% Create figure
f1 = figure('WindowStyle','normal','Position',[100,200,600+(50*n_rois),600]);

% Beautiful box chart
b1 = boxchart(label_rois(:),mat_QSM(:),'GroupByColor',~label_hc(:));
box on; hold on;

% Line at chi=0
plot([0,n_rois+1],[0,0],'k--');

% Lines separating basal ganglia
plot([10.5,10.5],[chi_min - (1*gsp),chi_max + (1*gsp)],'k:','LineWidth',2);
plot([11.5,11.5],[chi_min - (1*gsp),chi_max + (1*gsp)],'k:','LineWidth',2);

% Labels and axes
axis([0.5,n_rois+0.5,chi_min - (1*gsp),chi_max + (1*gsp)]);
ylabel('Susceptibility (ppm)');
xticks(1:n_rois);
xticklabels(roi_titles);
set(gca,'FontSize',14);
b1(1).BoxFaceColor = colour.g;
b1(2).BoxFaceColor = colour.p;
b1(1).MarkerColor = colour.g;
b1(2).MarkerColor = colour.p;

% Plot significance lines and stars
for rr = 1:n_rois

    if pval_QSM(rr) < 0.05

        % Figure out the right height to put the line
        sigline_y = max(mat_QSM(:,rr)) + (1.*gsp);
        
        % Plot the line
        plot([rr-0.3,rr+0.3],[sigline_y,sigline_y],'k-','LineWidth',2);

        % Display a star
        text(rr,sigline_y+0.5*gsp,'*','HorizontalAlignment','center','FontSize',16);

    end

end % for rr = 1:n_rois 

set(gca,'FontSize',16);

% Create the legend at the end
legend('Healthy Controls','SCA Subjects','','Location','SouthWest');


%% Save the QSM plot

exportgraphics(f1,'ROIbox_allBG_QSM.tif');


%% Box Plot of R2-star Values

gsp = 0.75; % spacing variable for the significance stars

% Max and min values for the y-axis
chi_min = min(mat_R2s(:));
chi_max = max(mat_R2s(:));

% Create figure
f2 = figure('WindowStyle','normal','Position',[100,300,600+(50*n_rois),600]);

% Beautiful box chart
b2 = boxchart(label_rois(:),mat_R2s(:),'GroupByColor',~label_hc(:));
box on; hold on;

% Line at chi=0
plot([0,n_rois+1],[0,0],'k--');

% Lines separating basal ganglia
plot([10.5,10.5],[chi_min - (1*gsp),chi_max + (1*gsp)],'k:','LineWidth',2);
plot([11.5,11.5],[chi_min - (1*gsp),chi_max + (1*gsp)],'k:','LineWidth',2);

% Labels and axes
axis([0.5,n_rois+0.5,chi_min - (1*gsp),chi_max + (1*gsp)]);
ylabel('R_2* (s^-^1)');
xticks(1:n_rois);
xticklabels(roi_titles);
set(gca,'FontSize',14);
b2(1).BoxFaceColor = colour.g;
b2(2).BoxFaceColor = colour.p;
b2(1).MarkerColor = colour.g;
b2(2).MarkerColor = colour.p;

% Plot significance lines and stars
for rr = 1:n_rois

    if pval_R2s(rr) < 0.05

        % Figure out the right height to put the line
        sigline_y = max(mat_R2s(:,rr)) + (1.*gsp);
        
        % Plot the line
        plot([rr-0.3,rr+0.3],[sigline_y,sigline_y],'k-','LineWidth',2);

        % Display a star
        text(rr,sigline_y+0.5*gsp,'*','HorizontalAlignment','center','FontSize',16);

    end

end % for rr = 1:n_rois 

set(gca,'FontSize',16);

% Create the legend at the end
legend('Healthy Controls','SCA Subjects','','Location','SouthWest');

%% Save out the R2* plot

exportgraphics(f2,'ROIbox_allBG_R2s.tif');